- README.md
Update documentation: replaced non-working Gitroom link with Postiz link in README to point to valid Quickstart documentation
Docs update
The original Gitroom link was non-functional and has been replaced with a Postiz link to ensure access to up-to-date and accurate documentation. 
> Fixed Quickstart link in README to point to Postiz documentation

- apps/docs/emails.mdx
- apps/docs/howitworks.mdx
- apps/docs/quickstart.mdx
This just simplifies some of the quickstart instructions for end users (most people don't care that it's a nextjs app, etc), and need to have it explained that there isn't a docker image (yet). I also pulled the postgres/redis instructions up, as it makes sense to do those either as standalone containers, or, using docker-compose, etc. 
Also cleaned up the email page a bit. 
Make it easier for end users!
> doc: Simplify quickstart instructions for end users

- .github/workflows/build.yaml
- **What kind of change does this PR introduce?**
@jonathan-irvin Current builds on this job are not actually using the cache, I think this may be due to having a cache key not set (like I did with the eslint job), so it makes sense to add it here to at least be the same as the other job.
> ci: Add cache key to build job

- .github/workflows/build-containers.yml
This just allows the containers job to be started manually.
> ci: Allow building containers as a manually started job

- .github/workflows/build-containers.yml
Just use primitive timestamps for now for container versions while we get things going.
> ci: Add timestamp to container as primitive version

- .github/workflows/build.yaml
- .github/workflows/codeql.yml
- .github/workflows/eslint.yaml
This will restrict GitHub actions to only run when certain paths change. This is to avoid actions running for silly reasons (eg, docs changing triggers a eslint).
> ci: only run actions when certain paths change

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build-containers.yml
CI change
This will tag new builds of container images with the latest tag, making it easy for container upgrades. 
**Other information:
> ci: Add latest tag to containers with each build

- apps/frontend/src/components/auth/register.tsx
feature
Lots of people seem to get errors when trying to register their first user, this should helpfully soften it. 
This also fixes a few bugs;
- Registration errors that are not HTTP 400 (eg, CORS errors, HTTP 404, etc) will now render an error message (previously nothing happened from a user's perspective).
- If the user doesn't need activating, they are redirected to the login page. 
Very new to coding with react, I'm not sure what is idiomatic at the moment, so just gave this a go as a relatively small change.
> feat: Better registration errors

- libraries/react-shared-libraries/src/form/checkbox.tsx
Bug Fix
Fixes #266. Checkbox tick is visible now on both modes.
**Dark Mode:**
**Light Mode:**
**Additional Comment:**
As per this PR checked.svg file is not used. So please confirm if I can remove `apps/public/form` folder
>  fix: Checkbox tick visible on both modes

- Dockerfile.dev
feature
This adds the default /uploads path which is necessary for the upcomming plugable storage change.
Discussing with Sanad and Nevo in the "pluggable storage" topic on Discord.
I am maint :-)
> ci: Add /uploads to Docker containers [skip ci]

- .gitignore
- docker-compose.dev.yaml
- package.json
Improvements:
- added npm script to run the docker-compose for local development. `npm run dev:docker`
- added volta pin to latest node LTS version `20.17.0` (lts/iron)
- added Redis web UI for the developer so that we can check the Redis state in a nice way
- switch docker images to the latest/alpine versions, which have much smaller sizes of docker images (save some space)
It makes setup for local development easier.
> [AB-0001]: added web ui for redis docker-compose.dev.yaml

- apps/frontend/src/components/layout/layout.settings.tsx
Bugfix
Fixes #362 
Before:
[Postiz-logo-overflow.webm](https://github.com/user-attachments/assets/c1fb7aa1-cc4c-42ad-927e-122843fc51cf)
After: 
[Postiz-logo-overflow-fix.webm](https://github.com/user-attachments/assets/3c14af4c-962a-4d22-a0b9-80b9a3e62db2)
> fix: prevent logo height from overflowing into title

- apps/frontend/src/components/launches/filters.tsx
- apps/frontend/src/components/layout/layout.settings.tsx
- apps/frontend/src/components/layout/mode.component.tsx
- apps/frontend/src/components/media/media.component.tsx
Fix overflow of Media Library,
Added Curser Pointer to Dark-Mode button & Next, Previous Button
eg: Bug fix, feature, docs update, ...
eg: Did you discuss this change with anybody before working on it (not required, but can be a good idea for bigger changes). Any plans for the future, etc?
> Fix: minor UI issues

- libraries/react-shared-libraries/src/helpers/uppy.upload.ts
Bug fix
This fixes upload errors with files < 100MB by forcing Uppy to always use multipart. Otherwise it would try to use singlepart and there is no presigning iomplemented for this case.
Was discussed on Discord
> Enable multipart uploads for all cloudflare uploads via uppy.

- apps/frontend/src/components/launches/providers/discord/discord.provider.tsx
Closes #378 
Bug fix regarding the issue where maximum amount of characters is set to 280 before being truncated, despite Discord's character limit is way higher.
This PR addresses the issue where messages sent to Discord through Postiz were being truncated at 280 characters, despite Discord’s actual character limit being 2000 characters. The change increases the `maxCharacter` limit in Postiz to 1980 to better align with Discord’s limit while keeping a slight buffer to account for any additional metadata Discord may attach, such as special formatting or potential future changes in message structure.
Having a buffer also improves reliability by reducing the risk of unexpected truncation or errors due to reaching the exact character limit in cases of small variations.
This issue was …
> Increase Discord Message Character Limit for Better Compatibility

- apps/frontend/src/components/analytics/chart-social.tsx
- apps/frontend/src/components/analytics/chart.tsx
- apps/frontend/src/components/billing/main.billing.component.tsx
- apps/frontend/src/components/launches/bot.picture.tsx
- apps/frontend/src/components/launches/calendar.context.tsx
- apps/frontend/src/components/launches/calendar.tsx
- apps/frontend/src/components/launches/editor.tsx
- apps/frontend/src/components/launches/generator/generator.tsx
- apps/frontend/src/components/launches/helpers/linkedin.component.tsx
- apps/frontend/src/components/launches/launches.component.tsx
- apps/frontend/src/components/layout/layout.context.tsx
- apps/frontend/src/components/layout/layout.settings.tsx
- apps/frontend/src/components/marketplace/preview.popup.dynamic.tsx
- apps/frontend/src/components/onboarding/connect.channels.tsx
- apps/frontend/src/components/platform-analytics/render.analytics.tsx
eg: Bug fix, feature, docs update, ...
eg: Did you discuss this change with anybody before working on it (not required, but can be a good idea for bigger changes). Any plans for the future, etc?
> Fix: removed unused variables, exported name as a property of default import #381

- apps/frontend/src/app/global.scss
- apps/frontend/src/components/launches/add.edit.model.tsx
- apps/frontend/src/components/launches/filters.tsx
- apps/frontend/src/components/launches/general.preview.component.tsx
- apps/frontend/src/components/launches/launches.component.tsx
- apps/frontend/src/components/layout/impersonate.tsx
- apps/frontend/src/components/layout/layout.settings.tsx
- apps/frontend/src/components/layout/top.menu.tsx
- apps/frontend/src/components/notifications/notification.component.tsx
TODO: Writing description - come back in a few mins
This PR introduces a functional responsive UI for at least the "launches" part of the web interface, which is obviously the most important. I didn't want to go /too/ far, but at least this makes Positz pretty usable on mobile. 
Below are many before/after screenshots. 
Problems;
* The page scrolls sideways
* The header menu scrolls off the page
* The "systray icons" are off the page
* The calendar is too small to be usable or clickable
Just posting this to prove I didn't break compatibility with the current UI. 
The header automatically re-organizes to make use of the minimal screen space, and automatically expands to the full-width in the above desktop version. Zero side-scrolling in a screen width of just 390px. :-)
Problems;
* Cancel …
> feature: Responsive launches UI

- libraries/nestjs-libraries/src/integrations/social/x.provider.ts
Bug fix
Inconsistency
Took me quite a while to figure out why, the X integration wasn't working. These variables are nowhere documented, and as it seems also outdated.
> Rename old TWITTER_CLIENT_ID(and SECRET) to new X_CLIENT_ID naming convention

- apps/frontend/src/components/settings/teams.component.tsx
Fix syntax break in 21d5b01f4721f9e37e8625f40d93a304b97dbe4a
> bugfix: Component property needs braces

- apps/frontend/src/components/launches/calendar.tsx
- apps/frontend/src/components/launches/filters.tsx
- apps/frontend/src/components/launches/helpers/date.picker.tsx
- apps/frontend/src/components/launches/helpers/isuscitizen.utils.tsx
It finds out the users preferred language and displays the time and date based on that
The change needed was that the American people weren't able to understand the dates in the original format
This solves the issue #156
I added a utility function that checks the current preference the user requires, and change the format of the displayed dates in the dayjs library based on it)
None
> [FEAT] change dates to the American people #156
