CODE_OF_CONDUCT.md
=> added code_of_conduct.md

apps/frontend/components/auth/register.tsx
I controlled the button using a state changing upon submitting the registration
=> made the registration button controlled

apps/frontend/components/analytics/analytics.component.tsx
=> Fixed Insufficient Color Contrast

README.md
Badge added: License, Issue, PR, Fork, Star and Change '.' to '|' to differentiate different topics
=> Added badge in the Github Readme

apps/frontend/components/votes/votes.component.tsx, apps/frontend/tailwind.config.js
Improve styles of the votes table
=> Improve style of votes table

apps/frontend/components/auth/register.tsx, apps/frontend/components/settings/settings.tsx
@nevo-david @garrrikkotua I have added the toast message for copy to clipboard in settings section kindly merge :)
Fixes #93 
---
---
=> fix: copy to clipboard

apps/backend/.env.example, apps/backend/src/shared/mail/mail.module.ts, apps/backend/src/shared/mail/mail.service.ts, apps/backend/src/shared/mail/providers/resend.api.ts, apps/backend/src/shared/mail/templates/example.hbs, apps/backend/src/shared/shared.module.ts
Added functionality for sending emails. Tested with `Resend` email API and more Apis/Smtps can be added in a similar way under `/providers` directory.
1. Populate .env variables starting with `EMAIL` (Refer .env.example) and start the server
2. import & define `MailService` using:
```typescript
import { MailService } from '@clickvote/backend/src/shared/mail/mail.service';
// And declare it in Class constructor of service/controller/otherLogicLayers something like below
constructor(
private _mailer: MailService
) {}
``` 
3. Now, send an email using the asynchronous `.sendMail()` function belonging to the mailer service:
```typescript
await this._mailer.sendMail(
'passionate_clickvote_sponsor@clickvote.dev', # Recipient Address
'Here goes the SUBJECT', #subject
'the plaintext version of …
```
=> Feat: Setup Mail Service + `Resend` added as Provider

apps/frontend/src/components/notifications/notification.component.tsx
=> feat: display loader while notifications are loading

CODE_OF_CONDUCT.md
#167 
Community
This change was necessary to establish clear guidelines for community behavior, ensuring a welcoming and inclusive environment for all contributors. By implementing a Code of Conduct, we aim to uphold mutual respect, professionalism, and collaboration, fostering a healthier and more productive community for everyone involved.
=> Add: Code of Conduct for Better Collaboration

.env.example, apps/docs/quickstart.mdx, docker-compose.dev.yaml
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Add docker compose file with redis & postgres configured
- Update `.env.example` to reflect connection string format
- Update `quickstart.mdx` to reflect docker compose usage
**Why was this change needed?** (You can also link to an open issue here)
Closes #164 
**Other information**:
=> Add docker compose file for local development

apps/docs/quickstart.mdx
Doc update
The installation instructions order was incorrect. Docker containers(database) should be started before running the migration.
=> Installation document correction

apps/docs/quickstart.mdx
fix typo.
PostgresSQL -> PostgreSQL
=> docs: update quickstart.mdx

libraries/nestjs-libraries/src/integrations/social/reddit.provider.ts
=> fix reddit title

package.json
[feat reset of db to start from scratch
makes it handy to start from 0
=> feat reset of db to start from scratch

.github/workflows/eslint.yaml
This action is a little bit different to what I've done before, normally eslint just outputs issues to standard output, but the configuration here saves a "sarif file", which I've not used before. 
Helps maintain the quality of the code when several people are comitting!
=> GitHub action eslint

.github/workflows/codeql.yml
- **What kind of change does this PR introduce?**
This change adds automatic, free code quality scanning in GitHub actions. Security or other issues will be reported in future pull requests, and in the security tab. 
It helps open source projects get better quality contributions.
=> feat: GitHub action codeql

apps/frontend/src/app/layout.tsx, package-lock.json, package.json
Bug Fix
Testing out a change for CI to allow for lazy-loading fonts
=> fix: font reload issues with next/font

.github/workflows/build.yaml
Add NextJS build cache as per their docs; https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
=> Add NEXT JS Build cache

.github/workflows/build-containers.yml
=> ci: Correct buildscript in container

.github/workflows/build-containers.yml
bugfix, several typos of "gitroom" as "github"!
=> bugfix: github typo in docker workflow

.github/PULL_REQUEST_TEMPLATE.md
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs
**Why was this change needed?** (You can also link to an open issue here)
The PR template formatting is just annoying :-) 
None
=> doc: Pull request template formatting

apps/frontend/src/app/global.scss, apps/frontend/src/components/layout/settings.component.tsx
**1. make the rounded edges of the Save button** 
**2. Added hover effect on the  remove button : 
Dark Mode  : 
on hover :** 
without hover : 
**Light Mode**
**on hover** 
**without hover :** 
**3. Percentage bar of uploading image  :**
=> Fixed 🐛 Bug Report :  Profile Settings UI errors [fixed : #301]  

apps/frontend/src/components/billing/billing.component.tsx, apps/frontend/src/components/billing/faq.component.tsx
Fixes #307
To provide a clear FAQ.
Any suggestions or feedback from the maintainers are appreciated.
=> fix: updated faq descriptions

CONTRIBUTING.md
Fixes #285 
Doc Update
The current CONTRIBUTING.md file lacks clarity and detail, which may make it difficult for new contributors to understand how to effectively participate in the project.
Please link to related issues when possible: Issue #285
=> doc: Update CONTRIBUTING.md 

apps/frontend/src/components/launches/filters.tsx
Bug fix
Fixes #310 
Before: 
https://github.com/user-attachments/assets/8cc03d69-d377-48cd-93e5-3a42f145cf22
After: 
https://github.com/user-attachments/assets/2196b4c7-56b0-44f4-a6b7-e944e96603ae
=> fix:Change button cursor to pointer on hover

apps/frontend/src/components/auth/login.tsx, apps/frontend/src/components/auth/register.tsx
This PR introduces a bug fix, it modifies the styling of the authentication button to have rounded edges, enhancing the user interface.
This change was needed to improve the visual appeal and user experience of the auth page, login page. It addresses [issue #257 ], where users mentioned that the button design was inconsistent. Making the edges rounded aligns with design standards.
No, as I thought it was a small fix (less than 3 lines of change).
=> Updated button style to rounded edges

var/docker/Caddyfile
Feature
Prelude to pluggable storage.
Working with sanad and nevo on this in discord.
=> Proxy /uploads in containers

apps/frontend/src/components/layout/continue.provider.tsx
- feat: variables
- feat: fix frontend provider
=> fix frontend

apps/frontend/src/app/layout.tsx
- feat: variables
- feat: fix frontend provider
- feat: fix storage provider
=> fix storage provider

SECURITY.md
eg: Bug fix, feature, docs update, ...
404 - page not found #353
eg: Did you discuss this change with anybody before working on it (not required, but can be a good idea for bigger changes). Any plans for the future, etc?
=> Fix: 404 - page not found #353

apps/frontend/src/components/launches/filters.tsx, apps/frontend/src/components/layout/mode.component.tsx
Bug fix
Fixes #360 
Before:
[postiz-button-hover-b.webm](https://github.com/user-attachments/assets/146b9949-ac91-4b92-9abc-8fc17ac52aca)
After:
[postiz-button-hover-a.webm](https://github.com/user-attachments/assets/884bda7b-d457-4cc3-8297-0fc3f0f48a9f)
=> Fix: Change button cursor to pointer on hover

package-lock.json
security
Depbump - reduces `npm audit` issues. from 4 to 3 issues.
=> security: depbump 2024-10-22

libraries/nestjs-libraries/src/integrations/social/bluesky.provider.ts
=> bugfix: #394 Bluesky posts now support "richtext" (URLs, tags, etc)

apps/backend/src/api/routes/copilot.controller.ts
=> bugfix: Console warning message instead of stacktrace if OPENAI_API_KEY is not set

apps/frontend/src/components/launches/providers/bluesky/bluesky.provider.tsx
=> bugfix: 300 character limit in Bluesky

libraries/helpers/src/utils/use.fire.events.ts
- feat: posthog
- feat: fix posthog
- feat: variables
=> identification

apps/backend/src/api/routes/auth.controller.ts, apps/backend/src/api/routes/public.controller.ts, apps/backend/src/api/routes/users.controller.ts, apps/backend/src/main.ts, apps/backend/src/services/auth/auth.middleware.ts, apps/frontend/src/app/layout.tsx, apps/frontend/src/components/layout/impersonate.tsx, apps/frontend/src/components/layout/layout.context.tsx, apps/frontend/src/components/layout/logout.component.tsx, apps/frontend/src/middleware.ts, libraries/helpers/src/utils/custom.fetch.func.ts, libraries/helpers/src/utils/custom.fetch.tsx, libraries/react-shared-libraries/src/helpers/variable.context.tsx
- feat: register once
- feat: not secured
=> Not secured

Jenkinsfile
Feature of Build Reports in CI/CD of Jenkins.
https://github.com/gitroomhq/postiz-app/issues/649 I'm Working on this third issue, I have recently completed a feature of Running tests and the test reports after solved this issue, We faces a problem of Build reports. We don't have a build report in CI/CD Status. So, I have worked on this issue.
I have completely discussed with @egelhaus and after discussion I'm try to working on this issue.
=> Add functionality of build reports in CI/CD in Jenkinsfile.

apps/backend/src/api/api.module.ts, apps/backend/src/api/routes/mcp.controller.ts, apps/backend/src/app.module.ts, apps/backend/src/mcp/main.mcp.ts, apps/backend/src/mcp/mcp.module.ts, apps/frontend/src/app/(preview)/p/[id]/layout.tsx, apps/frontend/src/components/launches/helpers/use.formatting.ts, apps/frontend/src/components/public-api/public.component.tsx, libraries/nestjs-libraries/src/integrations/integration.manager.ts, libraries/nestjs-libraries/src/integrations/social/instagram.provider.ts, libraries/nestjs-libraries/src/integrations/social/x.provider.ts, libraries/nestjs-libraries/src/mcp/mcp.service.ts, libraries/nestjs-libraries/src/mcp/mcp.settings.ts, libraries/nestjs-libraries/src/mcp/mcp.tool.ts, libraries/nestjs-libraries/src/mcp/mcp.transport.ts, libraries/nestjs-libraries/src/mcp/mcp.types.ts, package-lock.json, package.json
- feat: mcp first version
- feat: package json
=> First version of MCPs

libraries/nestjs-libraries/src/integrations/social/threads.provider.ts, libraries/nestjs-libraries/src/integrations/social/x.provider.ts, package.json, pnpm-lock.yaml
- feat: changes
- feat: threads refresh token implementation
=> Threads refresh token

.github/workflows/build-containers.yml, Dockerfile.dev, apps/backend/src/api/routes/media.controller.ts, apps/frontend/src/components/launches/ai.image.tsx, apps/frontend/src/components/launches/helpers/linkedin.component.tsx, apps/frontend/src/components/launches/helpers/media.settings.component.tsx, apps/frontend/src/components/launches/launches.component.tsx, apps/frontend/src/components/launches/polonto.tsx, apps/frontend/src/components/layout/layout.settings.tsx, apps/frontend/src/components/media/media.component.tsx, apps/frontend/src/components/media/new.uploader.tsx, apps/frontend/src/components/new-launch/editor.tsx, apps/frontend/src/components/new-launch/manage.modal.tsx, apps/frontend/src/components/new-launch/store.ts, apps/frontend/src/components/third-parties/third-party.media.tsx, libraries/nestjs-libraries/src/database/prisma/media/media.repository.ts, libraries/nestjs-libraries/src/database/prisma/media/media.service.ts, libraries/nestjs-libraries/src/database/prisma/schema.prisma, libraries/nestjs-libraries/src/dtos/media/save.media.information.dto.ts, libraries/react-shared-libraries/src/helpers/video.frame.tsx
- feat: assembly
- feat: thumb
- feat: thumbnails and alt
=> Thumbnails and alt
